### ISSUE TITLE
Hifi 4x4 integration

### ISSUE THREAD

**Issue by enry86cami** [excaliburpartners/HAILogger#27]
Hi, I'm using Omnilinkbridge with my omni2e central. My configuration include the HiFi 4x4, is planned its integration?

**Comment by rwagoner** [comment]
I've added audio support to the dev branch and dev tagged docker container. At this time there isn't a way to run the dev build if you are using the Home Assistant add-on version. Unfortunately, I don't have any audio zones so I'm unable to verify if it works. I know this issue is a few years old, but wanted to reach out in case you are still using this software.

**Comment by jlipsit** [comment]
> I've added audio support to the dev branch and dev tagged docker container. At this time there isn't a way to run the dev build if you are using the Home Assistant add-on version. Unfortunately, I don't have any audio zones so I'm unable to verify if it works. I know this issue is a few years old, but wanted to reach out in case you are still using this software.

Would this possibly work with my Russound or is this specific to the HAI HiFi hardware?

**Comment by rwagoner** [comment]
Nope not specific to HAI HiFi. It adds the following per audio zone.
MQTT Switch - Audio Zone Power On/Off
MQTT Switch - Audio Zone Mute On./Off
MQTT Select - Audio Zone Source
MQTT Number - Audio Zone Volume

**Comment by rwagoner** [comment]
Version 1.1.16 with audio support has been released. You should see an update for the OmniLink Bridge Home Assistant add-on available.
